class CountriesData {
  List data = [
    ['ar.svg', 'Argentina', 'ar'],
    ['au.svg', 'Australia', 'au'],
    ['at.svg', 'Austria', 'at'],
    ['be.svg', 'Belgium', 'be'],
    ['br.svg', 'Brazil', 'br'],
    ['bg.svg', 'Bulgaria', 'bg'],
    ['ca.svg', 'Canada', 'ca'],
    ['cn.svg', 'China', 'cn'],
    ['co.svg', 'Colombia', 'co'],
    ['cu.svg', 'Cuba', 'cu'],
    ['cz.svg', 'Czech Republic', 'cz'],
    ['eg.svg', 'Egypt', 'eg'],
    ['fr.svg', 'France', 'fr'],
    ['de.svg', 'Germany', 'de'],
    ['gr.svg', 'Greece', 'gr'],
    ['hk.svg', 'Hong Kong', 'hk'],
    ['hu.svg', 'Hungary', 'hu'],
    ['in.svg', 'India', 'in'],
    ['id.svg', 'Indonesia', 'id'],
    ['ie.svg', 'Ireland', 'ie'],
    ['il.svg', 'Israel', 'il'],
    ['it.svg', 'Italy', 'it'],
    ['jp.svg', 'Japan', 'jp'],
    ['lv.svg', 'Latvia', 'lv'],
    ['lt.svg', 'Lithuania', 'lt'],
    ['my.svg', 'Malaysia', 'my'],
    ['mx.svg', 'Mexico', 'mx'],
    ['ma.svg', 'Morocco', 'ma'],
    ['nl.svg', 'Netherlands', 'nl'],
    ['nz.svg', 'New Zealand', 'nz'],
    ['ng.svg', 'Nigeria', 'ng'],
    ['no.svg', 'Norway', 'no'],
    ['ph.svg', 'Philippines', 'ph'],
    ['pl.svg', 'Poland', 'pl'],
    ['pt.svg', 'Portugal', 'pt'],
    ['ro.svg', 'Romania', 'ro'],
    ['ru.svg', 'Russia', 'ru'],
    ['sa.svg', 'Saudi Arabia', 'sa'],
    ['rs.svg', 'Serbia', 'rs'],
    ['sg.svg', 'Singapore', 'sg'],
    ['sk.svg', 'Slovakia', 'sk'],
    ['si.svg', 'Slovenia', 'si'],
    ['za.svg', 'South Africa', 'za'],
    ['kr.svg', 'South Korea', 'kr'],
    ['se.svg', 'Sweden', 'se'],
    ['ch.svg', 'Switzerland', 'ch'],
    ['tw.svg', 'Taiwan', 'tw'],
    ['th.svg', 'Thailand', 'th'],
    ['tr.svg', 'Turkey', 'tr'],
    ['ae.svg', 'UAE', 'ae'],
    ['ua.svg', 'Ukraine', 'ua'],
    ['gb.svg', 'United Kingdom', 'gb'],
    ['us.svg', 'United States', 'us'],
    ['ve.svg', 'Venuzuela', 've'],
  ];

  List getCountriesData() {
    return data;
  }
}
